* Sun Nov 22 2017 Stephane de Labrusse <stephdl@de-labrusse.fr> 0.1.9-1.ns7 - find the UDP ports for dlna

diff --git a/root/etc/e-smith/events/actions/nethserver-madsonic-find-dlna-port b/root/etc/e-smith/events/actions/nethserver-madsonic-find-dlna-port
--- a/root/etc/e-smith/events/actions/nethserver-madsonic-find-dlna-port
+++ b/root/etc/e-smith/events/actions/nethserver-madsonic-find-dlna-port
@@ -32,5 +32,17 @@ UDPPortDlna=$(echo $(netstat -ulpn | grep $(cat /var/run/madsonic.pid) |
     grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b:[0-9]+" | 
     sed 's/[0-9]\{1,3\}.[0-9]\{1,3\}.[0-9]\{1,3\}.[0-9]\{1,3\}://g'))
 
+#make a regex to test if the port is right
+re='^[0-9]+$'
+
+if ! [[ $TCPPortDlna =~ $re ]] || [[ $UDPPortDlna -gt 65536 ]]; then
+   echo "Madsonic DLNA error: Not a TCP Port"
+   exit 1
+fi
+if ! [[ $UDPPortDlna =~ $re ]] || [[ $UDPPortDlna -gt 65536 ]]; then
+   echo "Madsonic DLNA error: Not a UDP Port"
+   exit 1
+fi
+
 /usr/sbin/e-smith/config set madsonic-dlna service TCPPort $TCPPortDlna UDPPorts 1900,$UDPPortDlna access green status enabled
 /usr/sbin/e-smith/signal-event firewall-adjust
